-- Caffè's extra function under Monopoly Mode
INSERT INTO Types
(Type, Kind)
VALUES
('BUILDING_TSUGU_SHOWCASE_gkls621', 'KIND_BUILDING');

INSERT INTO DistrictModifiers
(DistrictType, ModifierId)
VALUES
('DISTRICT_CAFFE_gkls621', 'CAFFE_GRANT_COFFEE_PRODUCT_gkls621'),
('DISTRICT_CAFFE_gkls621', 'CAFFE_GRANT_SHOWCASE_gkls621');

INSERT INTO TraitModifiers
(TraitType, ModifierId)
VALUES
('TRAIT_LEADER_TSUGUMI_gkls621', 'TSUGUMI_PALACE_PRODUCT_SLOT_gkls621');

INSERT INTO Modifiers
(ModifierId, ModifierType, RunOnce, Permanent)
VALUES
('CAFFE_GRANT_COFFEE_PRODUCT_gkls621', 'MODIFIER_PLAYER_GRANT_RANDOM_RESOURCE_PRODUCT', 1, 1),
('CAFFE_GRANT_SHOWCASE_gkls621',    'MODIFIER_SINGLE_CITY_GRANT_BUILDING_IN_CITY_IGNORE', 1, 1),
('TSUGUMI_PALACE_PRODUCT_SLOT_gkls621', 'MODIFIER_PLAYER_CITIES_ADJUST_EXTRA_GREAT_WORK_SLOTS', 0, 0);

INSERT INTO ModifierArguments
(ModifierId, Name, Value)
VALUES
('CAFFE_GRANT_COFFEE_PRODUCT_gkls621', 'ResourceType', 'RESOURCE_COFFEE'),
('TSUGUMI_PALACE_PRODUCT_SLOT_gkls621', 'Amount', 3),
('CAFFE_GRANT_SHOWCASE_gkls621', 'BuildingType', 'BUILDING_TSUGU_SHOWCASE_gkls621'),
('TSUGUMI_PALACE_PRODUCT_SLOT_gkls621', 'BuildingType', 'BUILDING_PALACE'),
('TSUGUMI_PALACE_PRODUCT_SLOT_gkls621', 'GreatWorkSlotType', 'GREATWORKSLOT_PRODUCT');


INSERT INTO Buildings
(BuildingType, Name, Description, PrereqDistrict, Cost, Maintenance, MustPurchase)
VALUES
('BUILDING_TSUGU_SHOWCASE_gkls621', 'LOC_BUILDING_TSUGU_SHOWCASE_gkls621_NAME', 'LOC_BUILDING_TSUGU_SHOWCASE_gkls621_DESCRIPTION',
'DISTRICT_JD_HOSPITAL', 1, 0, 1);

INSERT INTO Buildings_XP2
(BuildingType, Pillage)
VALUES
('BUILDING_TSUGU_SHOWCASE_gkls621', 0);

INSERT INTO Building_GreatWorks
(BuildingType,  GreatWorkSlotType,  NumSlots, ThemingYieldMultiplier, ThemingTourismMultiplier, ThemingSameObjectType, ThemingBonusDescription)
VALUES
('BUILDING_TSUGU_SHOWCASE_gkls621', 'GREATWORKSLOT_PRODUCT', 1, 100, 200, 1, 'LOC_BUILDING_TSUGU_SHOWCASE_gkls621_THEMING_BONUS');