-- Tomoe Traits
INSERT INTO Types
(Type,  Kind)
VALUES
('TRAIT_LEADER_TOMOE_gkls621', 'KIND_TRAIT');

INSERT INTO Traits
(TraitType,                     Name,                                   Description)
VALUES
('TRAIT_LEADER_TOMOE_gkls621', 'LOC_TRAIT_LEADER_TOMOE_gkls621_NAME', 'LOC_TRAIT_LEADER_TOMOE_gkls621_DESCRIPTION');

INSERT INTO LeaderTraits
(LeaderType,                TraitType)
VALUES
('LEADER_TOMOE_gkls621',   'TRAIT_LEADER_TOMOE_gkls621'),
('LEADER_TOMOE_gkls621',   'TRAIT_UNIT_TAIKO_TEAM_gkls621');

INSERT INTO TraitModifiers
(TraitType, ModifierId)
VALUES
('TRAIT_LEADER_TOMOE_gkls621', 'TOMOE_BABARIAN_CAMP_ENVOY_gkls621');
--('TRAIT_LEADER_TOMOE_gkls621', 'TOMOE_GOODY_HUT_ENVOY_gkls621');

INSERT INTO TraitModifiers
(TraitType, ModifierId)
SELECT DISTINCT
'TRAIT_LEADER_TOMOE_gkls621', 'TOMOE_UNITS_MOVEMENT_SUZERAIN_' || InheritFrom || '__gkls621'
FROM Leaders WHERE InheritFrom LIKE '%MINOR%';

INSERT INTO Modifiers
(ModifierId, ModifierType, SubjectRequirementSetId)
SELECT DISTINCT
'TOMOE_UNITS_MOVEMENT_SUZERAIN_' || InheritFrom || '__gkls621',
'MODIFIER_PLAYER_UNITS_ADJUST_MOVEMENT',
'REQSET_AG_PLAYER_SUZERAIN_OF_1_' || InheritFrom || '_gkls621'
FROM Leaders WHERE InheritFrom LIKE '%MINOR%';

INSERT INTO Modifiers
(ModifierId, ModifierType)
VALUES
('TOMOE_BABARIAN_CAMP_ENVOY_gkls621', 'MODIFIER_PLAYER_ADJUST_IMPROVEMENT_GOODY_HUT'),
--('TOMOE_GOODY_HUT_ENVOY_gkls621',     'MODIFIER_PLAYER_ADJUST_IMPROVEMENT_GOODY_HUT'),
('TOMOE_CAPITAL_SCIENCE_gkls621', 'MODIFIER_PLAYER_CAPITAL_CITY_ADJUST_CITY_YIELD_CHANGE'),
('TOMOE_CAPITAL_CULTURE_gkls621', 'MODIFIER_PLAYER_CAPITAL_CITY_ADJUST_CITY_YIELD_CHANGE'),
('TOMOE_CAPITAL_FAITH_gkls621', 'MODIFIER_PLAYER_CAPITAL_CITY_ADJUST_CITY_YIELD_CHANGE'),
('TOMOE_CAPITAL_GOLD_gkls621', 'MODIFIER_PLAYER_CAPITAL_CITY_ADJUST_CITY_YIELD_CHANGE'),
('TOMOE_CAPITAL_PRODUCTION_gkls621', 'MODIFIER_PLAYER_CAPITAL_CITY_ADJUST_CITY_YIELD_CHANGE'),
('TOMOE_CAPITAL_FOOD_gkls621', 'MODIFIER_PLAYER_CAPITAL_CITY_ADJUST_CITY_YIELD_CHANGE'),
('TOMOE_CAPITAL_AMENITY_gkls621', 'MODIFIER_AG_PLAYER_CAPITAL_CITY_ADJUST_TRAIT_AMENITY_gkls621'),
('TOMOE_CAPITAL_FAVOR_gkls621', 'MODIFIER_PLAYER_ADJUST_BUILDING_FAVOR');

INSERT INTO ModifierArguments
(ModifierId, Name, Value)
SELECT DISTINCT
'TOMOE_UNITS_MOVEMENT_SUZERAIN_' || InheritFrom || '__gkls621',
'Amount', 1
FROM Leaders WHERE InheritFrom LIKE '%MINOR%';

INSERT INTO ModifierArguments
(ModifierId, Name, Value)
VALUES
('TOMOE_BABARIAN_CAMP_ENVOY_gkls621', 'ImprovementType', 'IMPROVEMENT_BARBARIAN_CAMP'),
('TOMOE_BABARIAN_CAMP_ENVOY_gkls621',   'GoodyHutImprovementType', 'IMPROVEMENT_TOMOE_GOODY_gkls621'),
--('TOMOE_GOODY_HUT_ENVOY_gkls621', 'ImprovementType', 'IMPROVEMENT_GOODY_HUT'),
--('TOMOE_GOODY_HUT_ENVOY_gkls621',   'GoodyHutImprovementType', 'IMPROVEMENT_TOMOE_GOODY_gkls621'),
('TOMOE_CAPITAL_SCIENCE_gkls621', 'YieldType', 'YIELD_SCIENCE'),
('TOMOE_CAPITAL_SCIENCE_gkls621', 'Amount', '1'),
('TOMOE_CAPITAL_CULTURE_gkls621', 'YieldType', 'YIELD_CULTURE'),
('TOMOE_CAPITAL_CULTURE_gkls621', 'Amount', '1'),
('TOMOE_CAPITAL_FAITH_gkls621', 'YieldType', 'YIELD_FAITH'),
('TOMOE_CAPITAL_FAITH_gkls621', 'Amount', '1'),
('TOMOE_CAPITAL_GOLD_gkls621', 'YieldType', 'YIELD_GOLD'),
('TOMOE_CAPITAL_GOLD_gkls621', 'Amount', '1'),
('TOMOE_CAPITAL_PRODUCTION_gkls621', 'YieldType', 'YIELD_PRODUCTION'),
('TOMOE_CAPITAL_PRODUCTION_gkls621', 'Amount', '1'),
('TOMOE_CAPITAL_FOOD_gkls621', 'YieldType', 'YIELD_SCIENCE'),
('TOMOE_CAPITAL_FOOD_gkls621', 'Amount', '1'),
('TOMOE_CAPITAL_AMENITY_gkls621', 'Amount', '1'),
('TOMOE_CAPITAL_FAVOR_gkls621', 'BuildingType', 'BUILDING_PALACE'),
('TOMOE_CAPITAL_FAVOR_gkls621', 'Favor', '1');

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType)
SELECT DISTINCT
'REQSET_AG_PLAYER_SUZERAIN_OF_1_' || InheritFrom || '_gkls621', 'REQUIREMENTSET_TEST_ALL'
FROM Leaders WHERE InheritFrom LIKE '%MINOR%';

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
SELECT DISTINCT
'REQSET_AG_PLAYER_SUZERAIN_OF_1_' || InheritFrom || '_gkls621',
'AG_PLAYER_SUZERAIN_OF_1_' || InheritFrom || '_gkls621'
FROM Leaders WHERE InheritFrom LIKE '%MINOR%';

INSERT INTO Requirements
(RequirementId, RequirementType)
SELECT DISTINCT
'AG_PLAYER_SUZERAIN_OF_1_' || InheritFrom || '_gkls621',
'REQUIREMENT_PLAYER_IS_SUZERAIN_X_TYPE'
FROM Leaders WHERE InheritFrom LIKE '%MINOR%';

INSERT INTO RequirementArguments
(RequirementId, Name,   Value)
SELECT DISTINCT
'AG_PLAYER_SUZERAIN_OF_1_' || InheritFrom || '_gkls621',
'Amount', 1
FROM Leaders WHERE InheritFrom LIKE '%MINOR%'
UNION SELECT DISTINCT
'AG_PLAYER_SUZERAIN_OF_1_' || InheritFrom || '_gkls621',
'LeaderType', InheritFrom
FROM Leaders WHERE InheritFrom LIKE '%MINOR%';