-- Tomoe's Agenda
INSERT INTO Types
(Type,	Kind)
VALUES
('TRAIT_AGENDA_TOMOE_gkls621',    'KIND_TRAIT');

INSERT INTO Traits
(TraitType)
VALUES
('TRAIT_AGENDA_TOMOE_gkls621');

INSERT INTO Agendas
(AgendaType,	Name,	Description)
VALUES
('AGENDA_TOMOE_gkls621',	'LOC_AGENDA_TOMOE_gkls621_NAME',	'LOC_AGENDA_TOMOE_gkls621_DESCRIPTION');

INSERT INTO AiListTypes
(ListType)
VALUES
('TOMOE_PSEUDOYIELD_gkls621');

INSERT INTO AiLists
(ListType, AgendaType, System)
VALUES
('TOMOE_PSEUDOYIELD_gkls621', 'TRAIT_AGENDA_TOMOE_gkls621', 'PseudoYields');

INSERT INTO AiFavoredItems
(ListType, Item, Value)
VALUES
('TOMOE_PSEUDOYIELD_gkls621', 'PSEUDOYIELD_CLEAR_BANDIT_CAMPS', 10),
('TOMOE_PSEUDOYIELD_gkls621', 'PSEUDOYIELD_DIPLOMATIC_GRIEVANCE', -1);

INSERT INTO HistoricalAgendas
(LeaderType,	AgendaType)
VALUES
('LEADER_TOMOE_gkls621',	'AGENDA_TOMOE_gkls621');

INSERT INTO ExclusiveAgendas
(AgendaOne,	AgendaTwo)
VALUES
('AGENDA_TOMOE_gkls621',    'AGENDA_BARBARIAN_LOVER'),
('AGENDA_TOMOE_gkls621',    'AGENDA_CIVILIZED'),
('AGENDA_TOMOE_gkls621',	'AGENDA_SYCOPHANT'),
('AGENDA_TOMOE_gkls621',	'AGENDA_DARWINIST');

INSERT INTO AgendaPreferredLeaders
(AgendaType,	LeaderType,	PercentageChance)
VALUES
('AGENDA_EXPLORER',   'LEADER_TOMOE_gkls621',	30),
('AGENDA_CITY_STATE_PROTECTOR',  'LEADER_TOMOE_gkls621',   40),
('AGENDA_STANDING_ARMY',    'LEADER_TOMOE_gkls621', 40);

INSERT INTO AgendaTraits
(AgendaType,	TraitType)
VALUES
('AGENDA_TOMOE_gkls621',	'TRAIT_AGENDA_TOMOE_gkls621');

INSERT INTO TraitModifiers
(TraitType,	ModifierId)
VALUES
('TRAIT_AGENDA_TOMOE_gkls621', 'TRAIT_SHORT_LIFE_GRIEVANCE_DECAY'),
('TRAIT_AGENDA_TOMOE_gkls621', 'AGENDA_TOMOE_gkls621_CLEARS_BABARIAN_CAMPS'),
('TRAIT_AGENDA_TOMOE_gkls621', 'AGENDA_TOMOE_gkls621_IGNORES_BABARIAN_CAMPS');

INSERT INTO Modifiers
(ModifierId,	ModifierType,	SubjectRequirementSetId)
VALUES
('AGENDA_TOMOE_gkls621_CLEARS_BABARIAN_CAMPS',   'MODIFIER_PLAYER_DIPLOMACY_SIMPLE_MODIFIER',    'PLAYER_CLEARS_BARBARIAN_CAMPS'),
('AGENDA_TOMOE_gkls621_IGNORES_BABARIAN_CAMPS',   'MODIFIER_PLAYER_DIPLOMACY_SIMPLE_MODIFIER',    'PLAYER_IGNORES_BARBARIAN_CAMPS');

INSERT INTO ModifierArguments
(ModifierId,	Name,	Value)
VALUES
('AGENDA_TOMOE_gkls621_CLEARS_BABARIAN_CAMPS',   'InitialValue',					8),
('AGENDA_TOMOE_gkls621_CLEARS_BABARIAN_CAMPS',   'StatementKey',					'LOC_DIPLO_KUDO_LEADER_TOMOE_gkls621_AGENDA_CLEARS_BABARIAN_CAMPS'),
('AGENDA_TOMOE_gkls621_CLEARS_BABARIAN_CAMPS',   'SimpleModifierDescription',	    'LOC_DIPLO_MODIFIER_DESCRIPTION_TOMOE_gkls621_AGENDA_CLEARS_BABARIAN_CAMPS'),
('AGENDA_TOMOE_gkls621_IGNORES_BABARIAN_CAMPS',   'InitialValue',					-3),
('AGENDA_TOMOE_gkls621_IGNORES_BABARIAN_CAMPS',   'StatementKey',					'LOC_DIPLO_WARNING_LEADER_TOMOE_gkls621_AGENDA_IGNORES_BABARIAN_CAMPS'),
('AGENDA_TOMOE_gkls621_IGNORES_BABARIAN_CAMPS',   'SimpleModifierDescription',	    'LOC_DIPLO_MODIFIER_DESCRIPTION_TOMOE_gkls621_AGENDA_IGNORES_BABARIAN_CAMPS');

INSERT INTO ModifierStrings
(ModifierId,	Context,	Text)
VALUES
('AGENDA_TOMOE_gkls621_CLEARS_BABARIAN_CAMPS',	'Sample',	'LOC_TOOLTIP_SAMPLE_DIPLOMACY_ALL'),
('AGENDA_TOMOE_gkls621_IGNORES_BABARIAN_CAMPS', 'Sample',	'LOC_TOOLTIP_SAMPLE_DIPLOMACY_ALL');