-- Moca Traits
INSERT INTO Types
(Type,  Kind)
VALUES
('TRAIT_LEADER_MOCA_gkls621', 'KIND_TRAIT'),
('MODIFIER_AG_CAPITAL_CITY_GRANT_GREAT_PERSON_CLASS_IN_CITY_gkls621', 'KIND_MODIFIER');

INSERT INTO DynamicModifiers (ModifierType, EffectType, CollectionType)
VALUES
('MODIFIER_AG_CAPITAL_CITY_GRANT_GREAT_PERSON_CLASS_IN_CITY_gkls621', 'EFFECT_GRANT_GREAT_PERSON_CLASS_IN_CITY', 'COLLECTION_PLAYER_CAPITAL_CITY');

INSERT INTO Traits
(TraitType,                     Name,                                   Description)
VALUES
('TRAIT_LEADER_MOCA_gkls621', 'LOC_TRAIT_LEADER_MOCA_gkls621_NAME', 'LOC_TRAIT_LEADER_MOCA_gkls621_DESCRIPTION');

INSERT INTO LeaderTraits
(LeaderType,                TraitType)
VALUES
('LEADER_MOCA_gkls621',   'TRAIT_LEADER_MOCA_gkls621'),
('LEADER_MOCA_gkls621',   'TRAIT_UNIT_BABANBO_gkls621');

INSERT INTO TraitModifiers
(TraitType, ModifierId)
VALUES
--('TRAIT_LEADER_MOCA_gkls621', 'MOCA_GOVERNOR_POINT_gkls621'),
('TRAIT_LEADER_MOCA_gkls621', 'MOCA_FAITH_PATRONAGE_DISCOUNT_gkls621'),
('TRAIT_LEADER_MOCA_gkls621', 'MOCA_RIVER_GOVERNMENT_PLOT_FAITH_gkls621'),
('TRAIT_LEADER_MOCA_gkls621', 'MOCA_RIVER_GOVERNMENT_PLOT_FAITH_EXTRA_gkls621'),
('TRAIT_LEADER_MOCA_gkls621', 'MOCA_RIVER_DIPLOQUAT_PLOT_FAITH_gkls621'),
('TRAIT_LEADER_MOCA_gkls621', 'MOCA_RIVER_DIPLOQUAT_PLOT_FAITH_EXTRA_gkls621'),
('TRAIT_LEADER_MOCA_gkls621', 'MOCA_FAITH_PURCHASE_GOVERNMENT_gkls621'),
('TRAIT_LEADER_MOCA_gkls621', 'MOCA_FAITH_PURCHASE_DIPLOMATIC_gkls621'),
('TRAIT_LEADER_MOCA_gkls621', 'MOCA_ADJUST_IMPROVEMENT_GOVERNMENT_gkls621'),
('TRAIT_LEADER_MOCA_gkls621', 'MOCA_ADJUST_IMPROVEMENT_DIPLOMATIC_gkls621'),
('TRAIT_LEADER_MOCA_gkls621', 'MOCA_ALLOW_BABANBO_REVIVAL_gkls621');

/* INSERT INTO TraitModifiers
(TraitType, ModifierId)
SELECT
'TRAIT_LEADER_MOCA_gkls621', 'MOCA_GRANT_EXTRA_' || GreatPersonClassType || '_gkls621'
FROM GreatPersonClasses WHERE AvailableInTimeline = 1 AND (MaxPlayerInstances IS NULL OR MaxPlayerInstances > 1); */

INSERT INTO Modifiers
(ModifierId, ModifierType, SubjectRequirementSetId)
VALUES
--('MOCA_GOVERNOR_POINT_gkls621', 'MODIFIER_PLAYER_ADJUST_GOVERNOR_POINTS', NULL),
('MOCA_FAITH_PATRONAGE_DISCOUNT_gkls621', 'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_PATRONAGE_DISCOUNT_PERCENT', NULL),
('MOCA_RIVER_GOVERNMENT_PLOT_FAITH_gkls621', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'REQSET_AG_PLOT_ADJACENT_TO_GOVERNMENT_gkls621'),
('MOCA_RIVER_GOVERNMENT_PLOT_FAITH_EXTRA_gkls621', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'REQSET_AG_PLOT_ADJACENT_TO_GOVERNMENT_AND_BONUS_RESOURCE_gkls621'),
('MOCA_RIVER_DIPLOQUAT_PLOT_FAITH_gkls621', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'REQSET_AG_PLOT_ADJACENT_TO_DIPLOQUAT_gkls621'),
('MOCA_RIVER_DIPLOQUAT_PLOT_FAITH_EXTRA_gkls621', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'REQSET_AG_PLOT_ADJACENT_TO_DIPLOQUAT_AND_BONUS_RESOURCE_gkls621'),
('MOCA_FAITH_PURCHASE_GOVERNMENT_gkls621', 'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE', NULL),
('MOCA_FAITH_PURCHASE_DIPLOMATIC_gkls621', 'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE', NULL),
('MOCA_ADJUST_IMPROVEMENT_GOVERNMENT_gkls621', 'MODIFIER_PLAYER_ADJUST_VALID_IMPROVEMENT', 'PLAYER_HAS_GOVERNMENT_DISTRICT_REQUIREMENTS'),
('MOCA_ADJUST_IMPROVEMENT_DIPLOMATIC_gkls621', 'MODIFIER_PLAYER_ADJUST_VALID_IMPROVEMENT', 'REQSET_AG_PLAYER_HAS_DIPLOMATIC_QUARTER_gkls621'),
('MOCA_ALLOW_BABANBO_REVIVAL_gkls621',  'MODIFIER_PLAYER_ALLOW_PROJECT_CATHERINE',    NULL),
('MOCA_BABANBO_USUAL_POPULATION_PRODUCTION_gkls621', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION', NULL),
('MOCA_BABANBO_USUAL_CITIES_AMENITY_gkls621', 'MODIFIER_PLAYER_CITIES_ADJUST_TRAIT_AMENITY', NULL);

INSERT INTO Modifiers
(ModifierId, ModifierType, RunOnce, Permanent)
SELECT
'MOCA_GRANT_EXTRA_' || GreatPersonClassType || '_gkls621',
'MODIFIER_AG_CAPITAL_CITY_GRANT_GREAT_PERSON_CLASS_IN_CITY_gkls621', 1, 1
FROM GreatPersonClasses WHERE AvailableInTimeline = 1 AND (MaxPlayerInstances IS NULL OR MaxPlayerInstances > 1);

INSERT INTO ModifierArguments
(ModifierId, Name, Value)
VALUES
--('MOCA_GOVERNOR_POINT_gkls621', 'Delta', 1),
('MOCA_FAITH_PATRONAGE_DISCOUNT_gkls621', 'YieldType', 'YIELD_FAITH'),
('MOCA_FAITH_PATRONAGE_DISCOUNT_gkls621', 'Amount', 25),
('MOCA_RIVER_GOVERNMENT_PLOT_FAITH_gkls621', 'YieldType', 'YIELD_FAITH'),
('MOCA_RIVER_GOVERNMENT_PLOT_FAITH_gkls621', 'Amount', 2),
('MOCA_RIVER_GOVERNMENT_PLOT_FAITH_EXTRA_gkls621', 'YieldType', 'YIELD_FAITH'),
('MOCA_RIVER_GOVERNMENT_PLOT_FAITH_EXTRA_gkls621', 'Amount', 5),
('MOCA_RIVER_DIPLOQUAT_PLOT_FAITH_gkls621', 'YieldType', 'YIELD_FAITH'),
('MOCA_RIVER_DIPLOQUAT_PLOT_FAITH_gkls621', 'Amount', 2),
('MOCA_RIVER_DIPLOQUAT_PLOT_FAITH_EXTRA_gkls621', 'YieldType', 'YIELD_FAITH'),
('MOCA_RIVER_DIPLOQUAT_PLOT_FAITH_EXTRA_gkls621', 'Amount', 5),
('MOCA_FAITH_PURCHASE_GOVERNMENT_gkls621', 'DistrictType', 'DISTRICT_GOVERNMENT'),
('MOCA_FAITH_PURCHASE_DIPLOMATIC_gkls621', 'DistrictType', 'DISTRICT_DIPLOMATIC_QUARTER'),
('MOCA_ADJUST_IMPROVEMENT_GOVERNMENT_gkls621', 'ImprovementType', 'IMPROVEMENT_MOCA_GOV_gkls621'),
('MOCA_ADJUST_IMPROVEMENT_DIPLOMATIC_gkls621', 'ImprovementType', 'IMPROVEMENT_MOCA_DIP_gkls621'),
('MOCA_ALLOW_BABANBO_REVIVAL_gkls621', 'ProjectType', 'PROJECT_BABANBO_REVIVAL_gkls621'),
('MOCA_BABANBO_USUAL_POPULATION_PRODUCTION_gkls621', 'Amount', '4'),
('MOCA_BABANBO_USUAL_POPULATION_PRODUCTION_gkls621', 'YieldType', 'YIELD_PRODUCTION'),
('MOCA_BABANBO_USUAL_CITIES_AMENITY_gkls621', 'Amount', 1);

INSERT INTO ModifierArguments
(ModifierId, Name, Value)
SELECT
'MOCA_GRANT_EXTRA_' || GreatPersonClassType || '_gkls621',
'GreatPersonClassType', GreatPersonClassType
FROM GreatPersonClasses WHERE AvailableInTimeline = 1 AND (MaxPlayerInstances IS NULL OR MaxPlayerInstances > 1);

INSERT INTO ModifierArguments
(ModifierId, Name, Value)
SELECT
'MOCA_GRANT_EXTRA_' || GreatPersonClassType || '_gkls621',
'Amount', 1
FROM GreatPersonClasses WHERE AvailableInTimeline = 1 AND (MaxPlayerInstances IS NULL OR MaxPlayerInstances > 1);

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES
('REQSET_AG_PLAYER_HAS_BABANBO_STATUE_gkls621', 'REQUIREMENTSET_TEST_ALL'),
('REQSET_AG_PLAYER_HAS_DIPLOMATIC_QUARTER_gkls621', 'REQUIREMENTSET_TEST_ALL'),
('REQSET_AG_PLOT_ADJACENT_TO_GOVERNMENT_gkls621', 'REQUIREMENTSET_TEST_ALL'),
('REQSET_AG_PLOT_ADJACENT_TO_GOVERNMENT_AND_BONUS_RESOURCE_gkls621', 'REQUIREMENTSET_TEST_ALL'),
('REQSET_AG_PLOT_ADJACENT_TO_DIPLOQUAT_gkls621', 'REQUIREMENTSET_TEST_ALL'),
('REQSET_AG_PLOT_ADJACENT_TO_DIPLOQUAT_AND_BONUS_RESOURCE_gkls621', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
VALUES
('REQSET_AG_PLAYER_HAS_BABANBO_STATUE_gkls621', 'AG_PLAYER_HAS_BABANBO_STATUE_gkls621'),
('REQSET_AG_PLAYER_HAS_DIPLOMATIC_QUARTER_gkls621', 'AG_PLAYER_HAS_DIPLOMATIC_QUARTER_gkls621'),
('REQSET_AG_PLOT_ADJACENT_TO_GOVERNMENT_gkls621', 'AG_PLOT_ADJACENT_TO_GOVERNMENT_gkls621'),
('REQSET_AG_PLOT_ADJACENT_TO_GOVERNMENT_AND_BONUS_RESOURCE_gkls621', 'AG_PLOT_ADJACENT_TO_GOVERNMENT_gkls621'),
('REQSET_AG_PLOT_ADJACENT_TO_GOVERNMENT_AND_BONUS_RESOURCE_gkls621', 'AG_PLOT_ADJACENT_TO_BONUS_RESOURCE_gkls621'),
('REQSET_AG_PLOT_ADJACENT_TO_DIPLOQUAT_gkls621', 'AG_PLOT_ADJACENT_TO_DIPLOQUAT_gkls621'),
('REQSET_AG_PLOT_ADJACENT_TO_DIPLOQUAT_AND_BONUS_RESOURCE_gkls621', 'AG_PLOT_ADJACENT_TO_DIPLOQUAT_gkls621'),
('REQSET_AG_PLOT_ADJACENT_TO_DIPLOQUAT_AND_BONUS_RESOURCE_gkls621', 'AG_PLOT_ADJACENT_TO_BONUS_RESOURCE_gkls621');

INSERT INTO Requirements (RequirementId, RequirementType)
VALUES
('AG_PLAYER_HAS_BABANBO_STATUE_gkls621', 'REQUIREMENT_PLAYER_HAS_BUILDING'),
('AG_PLAYER_HAS_DIPLOMATIC_QUARTER_gkls621', 'REQUIREMENT_PLAYER_HAS_DISTRICT'),
('AG_PLOT_ADJACENT_TO_GOVERNMENT_gkls621', 'REQUIREMENT_PLOT_ADJACENT_DISTRICT_TYPE_MATCHES'),
('AG_PLOT_ADJACENT_TO_DIPLOQUAT_gkls621', 'REQUIREMENT_PLOT_ADJACENT_DISTRICT_TYPE_MATCHES'),
('AG_PLOT_ADJACENT_TO_BONUS_RESOURCE_gkls621', 'REQUIREMENT_PLOT_ADJACENT_RESOURCE_CLASS_TYPE_MATCHES');

INSERT INTO RequirementArguments (RequirementId, Name, Value)
VALUES
('AG_PLAYER_HAS_BABANBO_STATUE_gkls621', 'BuildingType', 'BUILDING_BABANBO_STATUE_gkls621'),
('AG_PLAYER_HAS_DIPLOMATIC_QUARTER_gkls621', 'DistrictType', 'DISTRICT_DIPLOMATIC_QUARTER'),
('AG_PLOT_ADJACENT_TO_GOVERNMENT_gkls621', 'DistrictType', 'DISTRICT_GOVERNMENT'),
('AG_PLOT_ADJACENT_TO_GOVERNMENT_gkls621', 'MaxRange', '1'),
('AG_PLOT_ADJACENT_TO_GOVERNMENT_gkls621', 'MinRange', '1'),
('AG_PLOT_ADJACENT_TO_DIPLOQUAT_gkls621', 'DistrictType', 'DISTRICT_DIPLOMATIC_QUARTER'),
('AG_PLOT_ADJACENT_TO_DIPLOQUAT_gkls621', 'MaxRange', '1'),
('AG_PLOT_ADJACENT_TO_DIPLOQUAT_gkls621', 'MinRange', '1'),
('AG_PLOT_ADJACENT_TO_BONUS_RESOURCE_gkls621', 'MaxRange', '1'),
('AG_PLOT_ADJACENT_TO_BONUS_RESOURCE_gkls621', 'MinRange', '1'),
('AG_PLOT_ADJACENT_TO_BONUS_RESOURCE_gkls621', 'ResourceClassType', 'RESOURCECLASS_BONUS');

/* INSERT INTO RequirementSets(RequirementSetId,   RequirementSetType)
SELECT DISTINCT
'REQSET_AG_PLAYER_HAS_' || GreatPersonClassType || '_gkls621',
'REQUIREMENTSET_TEST_ALL'
FROM GreatPersonClasses WHERE AvailableInTimeline = 1 AND (MaxPlayerInstances IS NULL OR MaxPlayerInstances > 1);

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
SELECT DISTINCT
'REQSET_AG_PLAYER_HAS_' || GreatPersonClassType || '_gkls621',
'AG_PLAYER_HAS_' || GreatPersonClassType || '_gkls621'
FROM GreatPersonClasses WHERE AvailableInTimeline = 1 AND (MaxPlayerInstances IS NULL OR MaxPlayerInstances > 1);

INSERT INTO Requirements (RequirementId, RequirementType)
SELECT DISTINCT
'AG_PLAYER_HAS_' || GreatPersonClassType || '_gkls621',
'REQUIREMENT_PLAYER_HAS_GREAT_PERSON_CLASS'
FROM GreatPersonClasses WHERE AvailableInTimeline = 1 AND (MaxPlayerInstances IS NULL OR MaxPlayerInstances > 1);

INSERT INTO RequirementArguments (RequirementId, Name, Value)
SELECT DISTINCT
'AG_PLAYER_HAS_' || GreatPersonClassType || '_gkls621',
'GreatPersonClass', GreatPersonClassType
FROM GreatPersonClasses WHERE AvailableInTimeline = 1 AND (MaxPlayerInstances IS NULL OR MaxPlayerInstances > 1); */